defmodule ConduitMcp.Session.EtsStore do
  @moduledoc """
  Default in-memory session store backed by a public, named ETS table.

  Sessions are keyed by `session_id` (a random URL-safe base64 string
  generated by `ConduitMcp.Session.generate_id/0` on first `initialize`)
  and store an arbitrary metadata map plus `"created_at"` (millisecond
  Unix timestamp).

  ## Ownership

  The table is owned by a long-lived `Agent` (`#{inspect(__MODULE__)}.Owner`)
  started from `ConduitMcp.Application`, so it outlives the short-lived
  Bandit request process that happens to touch it first. Without a supervised
  owner the table died with its creating request and every session created
  before that point was silently lost — `Session.get/2` returned
  `{:error, :not_found}` for a session id the client had just been handed.

  `ensure_table/0` remains as a fallback for embedding contexts where the
  `:conduit_mcp` application is not started (e.g. some test setups). It is
  not the primary mechanism.

  ## Concurrency

  The table is `:public, :set, read_concurrency: true, write_concurrency: :auto`.
  Reads do not block writes; writers serialize per key. Suitable for production
  single-node workloads. For multi-node deployments, implement a
  `ConduitMcp.Session.Store` against your distributed backend — see
  `guides/multi_node_sessions.md`.

  ## Bounds & cleanup

  Two mechanisms keep the table bounded, and both are needed:

    * **Row cap.** `create/2` refuses to grow the table past
      `config :conduit_mcp, :sessions_max_rows` (default
      #{100_000}, `:infinity` disables it) and returns
      `{:error, :session_limit_reached}`. Sessions are created by
      unauthenticated `initialize` requests, so without a cap a supervised
      (i.e. immortal) table is an unbounded growth surface.

      Note this is a *global* bound, not a per-caller one: it refuses new
      sessions rather than evicting existing ones, so an unauthenticated flood
      cannot displace a live session, but it can deny new ones until the
      janitor ages the flood out. `ConduitMcp.Plugs.RateLimit` is the
      per-caller bound; configure it on any public-facing transport.
    * **TTL sweep.** `cleanup/1` prunes rows older than a TTL.
      `ConduitMcp.Session.Janitor` is started by `ConduitMcp.Application`
      against this store by default; disable it with
      `config :conduit_mcp, :session_janitor, false`, or tune it with
      `config :conduit_mcp, :session_janitor, ttl: ..., interval: ...`.

  ## Configuration

  Reference the store from a transport's `:session` option:

      {ConduitMcp.Transport.StreamableHTTP,
       server_module: MyServer,
       session: [store: ConduitMcp.Session.EtsStore, ttl: :timer.minutes(60)]}
  """

  @behaviour ConduitMcp.Session.Store

  @table :conduit_mcp_sessions
  @table_opts [:named_table, :public, :set, read_concurrency: true, write_concurrency: :auto]

  # Sessions are created by unauthenticated `initialize` requests. The table
  # is now supervised and therefore immortal, so the cap is the only thing
  # bounding it between janitor sweeps.
  @default_max_rows 100_000

  @doc false
  def table_opts, do: @table_opts

  @doc """
  Ensures the ETS table exists.

  Normally a no-op: `#{inspect(__MODULE__)}.Owner` creates the table at
  application start. Retained so the store still works when `:conduit_mcp`
  is not running as an OTP application.
  """
  def ensure_table do
    if :ets.whereis(@table) == :undefined do
      :ets.new(@table, @table_opts)
    end

    :ok
  rescue
    # Lost check-then-create race: another process created the table first.
    ArgumentError -> :ok
  end

  @doc """
  Creates a session, unless the table is already at its configured row cap.

  Returns `:ok`, or `{:error, :session_limit_reached}`.
  """
  @impl true
  def create(session_id, metadata) do
    ensure_table()

    if at_capacity?() do
      {:error, :session_limit_reached}
    else
      entry =
        Map.merge(metadata, %{
          "created_at" => System.system_time(:millisecond)
        })

      :ets.insert(@table, {session_id, entry})
      :ok
    end
  end

  defp at_capacity? do
    case Application.get_env(:conduit_mcp, :sessions_max_rows, @default_max_rows) do
      :infinity -> false
      max when is_integer(max) -> :ets.info(@table, :size) >= max
    end
  end

  @impl true
  def get(session_id) do
    ensure_table()

    case :ets.lookup(@table, session_id) do
      [{^session_id, metadata}] -> {:ok, metadata}
      [] -> {:error, :not_found}
    end
  end

  @impl true
  def delete(session_id) do
    ensure_table()
    :ets.delete(@table, session_id)
    :ok
  end

  @impl true
  def update(session_id, new_metadata) do
    ensure_table()

    case :ets.lookup(@table, session_id) do
      [{^session_id, existing}] ->
        :ets.insert(@table, {session_id, Map.merge(existing, new_metadata)})
        :ok

      [] ->
        {:error, :not_found}
    end
  end

  @doc """
  Removes sessions older than `ttl_ms` milliseconds.
  """
  @impl true
  def cleanup(ttl_ms) do
    ensure_table()
    now = System.system_time(:millisecond)

    # Deleting the *current* element during `:ets.foldl` is guaranteed safe by
    # ETS for set tables — do NOT "fix" this into collect-then-delete.
    :ets.foldl(
      fn {session_id, metadata}, acc ->
        created_at = Map.get(metadata, "created_at", 0)

        if now - created_at > ttl_ms do
          :ets.delete(@table, session_id)
          acc + 1
        else
          acc
        end
      end,
      0,
      @table
    )
  end

  defmodule Owner do
    @moduledoc """
    Long-lived process that owns the `:conduit_mcp_sessions` ETS table so the
    table outlives short-lived request handlers.

    Started under `ConduitMcp.Supervisor` by `ConduitMcp.Application`. This is
    the same pattern used by `ConduitMcp.Tasks.EtsStore.Owner`,
    `ConduitMcp.Cancellation.Owner` and
    `ConduitMcp.OAuth.KeyProvider.JWKS.Owner`; sessions were the one ETS
    subsystem missing it.

    The Agent deliberately holds no state and answers no calls — reads and
    writes go directly to the `:public` table from the calling process. Do not
    turn it into a `handle_call` gateway.
    """

    # Not a GenServer itself: the process is a `ConduitMcp.EtsOwner`
    # registered under this module's name. This module is the child spec.
    def child_spec(opts) do
      %{id: __MODULE__, start: {__MODULE__, :start_link, [opts]}}
    end

    alias ConduitMcp.Session.EtsStore

    def start_link(_opts) do
      ConduitMcp.EtsOwner.start_link(__MODULE__, :conduit_mcp_sessions, EtsStore.table_opts())
    end
  end
end
